name: 'NumenActions NumenVet'
description: 'Vet charts'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/fiveateooate/numenactions:latest'
  entrypoint: '/usr/local/bin/numencli'
  args:
    - --loglevel
    - debug
    - vet
