#!/usr/bin/env python3

import argparse
import os
import sys

from numenactions import PolarisVetter, logger_setup
from termcolor import colored


def main():
    parser = argparse.ArgumentParser(description="NumenActions - They can do anything!")
    parser.add_argument(
        "--loglevel", help="log level", default=os.environ.get("LOGLEVEL")
    )
    parser.add_argument(
        "--assetpath", help="log level", default=os.environ.get("NUMEN_ASSET_PATH")
    )
    args = parser.parse_args()
    logger = logger_setup("numenactions", args.loglevel)

    logger.debug("runing changetype action")
    eddie = PolarisVetter(args.assetpath)
    (output, exitcode) = eddie.vet()
    if exitcode != 0:
        logger.info(colored(f"\n{output}", "yellow"))
    else:
        logger.debug(f"output {output}")
    return exitcode


if __name__ == "__main__":
    exitcode = main()
    sys.exit(exitcode)
