#!/usr/bin/env python3

import argparse
import os

import numenactions


def main():
    parser = argparse.ArgumentParser(description="NumenActions - They can do anything!")
    parser.add_argument(
        "--loglevel", help="log level", default=os.environ.get("LOGLEVEL")
    )
    parser.add_argument(
        "--assetpath", help="log level", default=os.environ.get("NUMEN_ASSSET_PATH")
    )
    args = parser.parse_args()
    logger = numenactions.logging.logger_setup("numenactions", args.loglevel)

    logger.debug("runing changetype action")
    eddie = numenactions.vetters.PolarisVetter()
    output = eddie.Vet(args.assetpath)
    logger.debug(f"output {output}")


if __name__ == "__main__":
    main()
